"""username

Revision ID: 5a09197f626d
Revises: e3c80d85a970
Create Date: 2025-10-14 06:40:50.320978

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a09197f626d"
down_revision: Union[str, None] = "e3c80d85a970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.add_column("users", sa.Column("avatar", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["username"])
    op.drop_column("users", "profileUrl")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("profileUrl", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "avatar")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
